services:
  - type: worker
    name: artvision-bot
    runtime: python
    region: frankfurt
    plan: free
    rootDir: bot
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ASANA_TOKEN
        sync: false
      - key: ASANA_WORKSPACE
        value: "860693669973770"
      - key: ASANA_PROJECT
        value: "1212305892582815"
      - key: ADMIN_IDS
        value: "161261562"
